/*
===============================================================
Magnitude Analysis Exploration
===============================================================
Purpose:
- To quantify the sales performance of products, customers, and categories.
- For understanding data distribution across different dimensions

SQL Functions Used:
- Aggregate Functions: SUM(), COUNT(), AVG()
- GROUP BY, ORDER BY
================================================================
*/

-- Find total customers by countries
SELECT 
    country,
    COUNT(customer_key) AS total_customers
FROM gold.dim_customers
GROUP BY country
ORDER BY total_customers DESC;

-- Find total customers by gender
SELECT 
    gender,
    COUNT(customer_key) AS total_customers
FROM gold.dim_customers
GROUP BY gender
ORDER BY total_customers DESC;

-- Find total products by category
SELECT
    category,
    COUNT(product_key) AS total_products
FROM gold.dim_products
GROUP BY category
ORDER BY total_products DESC;

-- What is the average cost in each category?
SELECT
    category,
    AVG(cost) AS avg_cost
FROM gold.dim_products
GROUP BY category
ORDER BY avg_cost DESC;

-- What is the total revenue generated for each category?
SELECT 
    p.category,
    SUM(s.sales_amount) AS total_revenue
FROM gold.fact_sales AS s
LEFT JOIN gold.dim_products AS p
    ON s.product_key = p.product_key
GROUP BY p.category
ORDER BY total_revenue DESC;

-- Find total revenue generated by each customer
SELECT 
    c.customer_key,
    c.first_name,
    c.last_name,
    SUM(f.sales_amount) AS total_revenue
FROM gold.fact_sales AS f 
LEFT JOIN gold.dim_customers AS c 
    ON c.customer_key = f.customer_key
GROUP BY c.customer_key, c.first_name, c.last_name
ORDER BY total_revenue DESC;

-- What is the distribution of sold items across the countries
SELECT
    c.country,
    COUNT(f.quantity) AS total_items_sold
FROM gold.fact_sales AS f
LEFT JOIN gold.dim_customers AS c 
    ON c.customer_key = f.customer_key
GROUP BY c.country
ORDER BY total_items_sold DESC;
